// <auto-generated />
using System;
using INETAssignment1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INETAssignment1.Migrations
{
    [DbContext(typeof(INETAssignment1Context))]
    [Migration("20251112152254_MoreTweaks")]
    partial class MoreTweaks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConcertGenre", b =>
                {
                    b.Property<int>("GenresgenreID")
                        .HasColumnType("int");

                    b.Property<int>("concertsconcertID")
                        .HasColumnType("int");

                    b.HasKey("GenresgenreID", "concertsconcertID");

                    b.HasIndex("concertsconcertID");

                    b.ToTable("ConcertGenre");
                });

            modelBuilder.Entity("INETAssignment1.Models.Band", b =>
                {
                    b.Property<int>("bandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bandID"));

                    b.Property<string>("bandDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genreID")
                        .HasColumnType("int");

                    b.HasKey("bandID");

                    b.HasIndex("genreID");

                    b.ToTable("Band");
                });

            modelBuilder.Entity("INETAssignment1.Models.Concert", b =>
                {
                    b.Property<int>("concertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("concertID"));

                    b.Property<int?>("bandID")
                        .HasColumnType("int");

                    b.Property<string>("concertName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("concertTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("locationID")
                        .HasColumnType("int");

                    b.Property<string>("tourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("concertID");

                    b.HasIndex("bandID");

                    b.HasIndex("locationID");

                    b.ToTable("Concert");
                });

            modelBuilder.Entity("INETAssignment1.Models.Genre", b =>
                {
                    b.Property<int>("genreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("genreID"));

                    b.Property<string>("genreDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genreID");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("INETAssignment1.Models.Location", b =>
                {
                    b.Property<int>("locationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("locationID"));

                    b.Property<string>("locationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("locationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("locationID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("INETAssignment1.Models.Purchase", b =>
                {
                    b.Property<int>("purchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("purchaseID"));

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<int>("concertID")
                        .HasColumnType("int");

                    b.Property<int>("creditCardNumber")
                        .HasColumnType("int");

                    b.Property<string>("customerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ticketsOrdered")
                        .HasColumnType("int");

                    b.HasKey("purchaseID");

                    b.HasIndex("concertID");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("ConcertGenre", b =>
                {
                    b.HasOne("INETAssignment1.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresgenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INETAssignment1.Models.Concert", null)
                        .WithMany()
                        .HasForeignKey("concertsconcertID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INETAssignment1.Models.Band", b =>
                {
                    b.HasOne("INETAssignment1.Models.Genre", "genre")
                        .WithMany("bands")
                        .HasForeignKey("genreID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("genre");
                });

            modelBuilder.Entity("INETAssignment1.Models.Concert", b =>
                {
                    b.HasOne("INETAssignment1.Models.Band", "headliningBand")
                        .WithMany("concerts")
                        .HasForeignKey("bandID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("INETAssignment1.Models.Location", "concertLocation")
                        .WithMany("concerts")
                        .HasForeignKey("locationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("concertLocation");

                    b.Navigation("headliningBand");
                });

            modelBuilder.Entity("INETAssignment1.Models.Purchase", b =>
                {
                    b.HasOne("INETAssignment1.Models.Concert", "Concert")
                        .WithMany("Purchases")
                        .HasForeignKey("concertID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("INETAssignment1.Models.Band", b =>
                {
                    b.Navigation("concerts");
                });

            modelBuilder.Entity("INETAssignment1.Models.Concert", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("INETAssignment1.Models.Genre", b =>
                {
                    b.Navigation("bands");
                });

            modelBuilder.Entity("INETAssignment1.Models.Location", b =>
                {
                    b.Navigation("concerts");
                });
#pragma warning restore 612, 618
        }
    }
}
